workflows:
  ios-release:
    name: iOS Release Build
    environment:
      vars:
        APP_STORE_CONNECT_PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ0ljNDEvMFZKQ1d4VkVvOFMKc09KeEl1NW9VN1FZSVJuK2ZMakFsTEZPcHErZ0NnWUlLb1pJemowREFRZWhSQU5DQUFRSG0vR3hvL2wvMlROVgpSRUdPeHJVM3E5VEs4ak5FU1dvVnAvSHg3NUhLYWdsNk1TUCtDVzZkbHhPMGhneGZYd2FMYkhteis2S1k3akFiCmlMSDg5UUFFCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
        APP_STORE_CONNECT_KEY_IDENTIFIER: "8VK2R3S8G9"
        APP_STORE_CONNECT_ISSUER_ID: "cdd1387f-182b-415b-9a5f-ef401500bf54"
    scripts:
      - name: Build iOS app
        script: |
          flutter build ipa --release
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
